[package]
name = "sound_garden"
version = "0.1.0"
authors = ["Ruslan Prokopchuk <fer.obbee@gmail.com>"]

[workspace]

[dependencies]
audio_graph = { path = "audio_graph" } 
cpal = "0"
find_folder = "0"
hashbrown = "0"
parking_lot = "0"
sciter-rs = "0"

[profile.release]
lto = true
